---
title: "Italy Polulation Density"
subtitle: "JHU - Coursera - Developing Data Product - Week 3 Assignment"
output: ioslides_presentation
date: '`r format(Sys.time(), "%d %B, %Y - %H:%M")`'
author: "Daniele De Faveri"
---

```{r setup, include=TRUE, echo = FALSE, warning= FALSE, message=FALSE,results = 'asis'}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)

library(dplyr)
library(plotly)

library(RColorBrewer)

library(geojson)
library(geojsonio)

```

## Italy Region Population Density
Plotly Chart of the italian population by region
`r Sys.Date()`

```{r data_prep, include=TRUE, echo = FALSE, warning= FALSE, message=FALSE,results = 'asis'}

Italy <- "https://raw.githubusercontent.com/stefanocudini/leaflet-geojson-selector/master/examples/italy-regions.json"

# read as text file
Italydoc <- readLines(Italy)

# write out as a temp file and read
tmpdir = tempdir()
write(Italydoc, file = paste0(tmpdir,"ITALYgeo.json"))

ITALYRegion <- geojson_read(paste0(tmpdir,"ITALYgeo.json"), what = "sp")

ITALYRegion@data <- ITALYRegion@data %>% mutate(Regione = gsub(" ","",name ) ) %>% 
  mutate( name  = gsub("[[:punct:]]","",name ) ) %>% mutate(Regione = gsub(" ","",name ) )


LivelliItalia <- as.data.frame( cbind(Regione = c('piemonte', 'valledaosta', 'lombardia', 'trentinoaltoadigesudtirol', 'veneto', 'friuliveneziagiulia', 'liguria', 'emiliaromagna', 'toscana', 'umbria', 'marche', 'lazio', 'abruzzo', 'molise', 'campania', 'puglia', 'basilicata', 'calabria', 'sicilia', 'sardegna'),
                                Pop = c('4375865', '126202', '10036258', '1067648', '4905037', '1215538', '1556981', '4452629', '3736968', '884640', '1531753', '5896693', '1315196', '308493', '5826860', '4048242', '567118', '1956687', '5026989', '1648176') ) )

ITALYRegion@data <- merge(ITALYRegion, LivelliItalia, by.x="Regione", by.y="Regione", all.x = TRUE)
ITALYRegion@data <- ITALYRegion@data %>% mutate(Pop = as.numeric(as.character(Pop)) , area = as.numeric(area) ) %>% mutate(density = Pop/area ) %>% mutate(Level=  cut(density, breaks=4, labels = c("Level.1","Level.2","Level.3","Level.4")))


colori.base2 <- c( "lightgreen","yellow", "orange","red" )
pal <- setNames(colori.base2, c("Level.1", "Level.2", "Level.3", "Level.4"))
data_to_plot <- ITALYRegion@data

t <- list(
  family = "sans serif",
  size = 14,
  color = toRGB("grey50"))

plot <- plot_ly(data = data_to_plot , x = ~area/1000/1000, y = ~Pop, color = ~Level, colors = pal, text = ~paste("Region: ", Regione, '<br>Population:', Pop, '<br>Area (km2):', area/1000/1000), size = ~Pop) %>% layout(title = 'Italian Region Population vs Area (Km2)',
         xaxis = list(title = 'Area (Km2)',
                      zeroline = TRUE),
         yaxis = list(title = 'Population'))
plot
```

## Thank You
